nextflow.enable.dsl=2

params.inputDir = 'input/'
params.outputDir = 'output'
params.multiqc = 'true'                 //multiqc is generated by default if no multiqc report is wanted add --multiqc="" when running the pipeline

// Quality filtering options
// Note: The options used below are from the fastp library
// Refer to fastp documentation for detailed information
// on these options: https://github.com/OpenGene/fastp
params.disable_quality_filtering = ''   //enter --disable_quality_filtering="-Q" to disable quality filtering
params.qualified_quality_phred = ''     //enter --qualified_quality_phred="-q int" int: the quality value that a base is qualified. Default 15 means phred quality is qualified, default: 15.
params.unqualified_percent_limit = ''   //enter --unqualified_percent_limit="-u int" int: how many percents of bases are allowed to be unqualified (0~100). Default 40 means .
params.n_base_limit = ''                //enter --n_base_limit="-n int" if one read's number of N base is >n_base_limit, then this read/pair is discarded. Default is 5 (int [=5])
params.average_qual = ''                //enter --average_qual="-e int" if one read's average quality score <avg_qual, then this read/pair is discarded. Default 0 means no requirement (int [=0])

// Length filtering options
params.disable_length_filtering = ''    //enter --disable_length_filtering="-L" length filtering is enabled by default. If this option is specified, length filtering is disabled
params.length_required = ''             //enter --length_required="-l int" int: reads shorter than length_required will be discarded, default is 15.
params.length_limit = ''                //enter --length_limit="--length_limit="--length_limit int" int: reads longer than length_limit will be discarded, default 0 means no limitation.

//Low complexity filtering
params.low_complexity_filter = ''       //enter --low_complexity_filter="-y" enable low complexity filter. The complexity is defined as the percentage of base that is different from its next base (base[i] != base[i+1]).
params.complexity_threshold = ''        //enter --complexity_threshold="-Y int" int: the threshold for low complexity filter (0~100). Default is 30, which means 30% complexity is required.


// multiqcChannel = Channel.fromPath(params.outputDir+'/reports') - could be deleted?


process CLEAN {
  container file(params.fastp_container_path)
  publishDir params.outputDir, mode: 'copy', overwrite:true

  input:
    path sequences

  output:
    path '${sequences.baseName}.output.fq', emit: fastq
    path '${sequences.baseName}_fastp_report/', emit: report

  script:
    """
    mkdir ${sequences.baseName}_fastp_report
    fastp -i ${sequences} -o ${sequences.baseName}.output.fq ${params.disable_quality_filtering} --html ${sequences.baseName}_fastp_report/${sequences.baseName}_fastp.html --json ${sequences.baseName}_fastp_report/${sequences.baseName}_fastp.json
    """
}

process MULTIQC {
  container file(params.multiqc_container_path)
  publishDir params.outputDir+'/reports', mode:'copy', overwrite:true

  input:
    path fastpReports

  output:
    path 'multiqc_report.html'

  script:
    """
    multiqc ${fastpReports}
    """
}


workflow fastp_multiqc_workflow {
  take: fastpChannel

  main:
    fastpChannel.view()
    fastpResChannel = CLEAN(fastpChannel)
    fastpResCollectedChannel = fastpResChannel.report.collect()
    MULTIQC(fastpResCollectedChannel)
  
  emit: 
    report = fastpResCollectedChannel
    fastq = fastpResChannel.fastq.collect()
}


workflow {
  fastpChannel = Channel.fromPath(params.inputDir+'/*.fq')
  fastp_multiqc_workflow(fastpChannel)
}
